# Generated by Django 3.2.7 on 2021-10-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoplist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneModel',
            new_name='Phone',
        ),
    ]
